FROM balenalib/raspberrypi3-debian-dotnet:3.1-sdk-stretch-build as build

WORKDIR /src
COPY ./balenaLocatingDashboard.csproj .

RUN dotnet restore "balenaLocatingDashboard.csproj"
COPY . .
RUN dotnet build "balenaLocatingDashboard.csproj" -o /app/build

FROM build AS publish
RUN dotnet publish "balenaLocatingDashboard.csproj" -o /app/publish

COPY --from=build /src/bin/Debug/netcoreapp3.1/ .
RUN ls -l
ENTRYPOINT  ["dotnet", "balenaLocatingDashboard.dll"]