FROM balenalib/intel-nuc-debian-dotnet:3.1-sdk-stretch-build as build
WORKDIR /app

#Restore nuget packages
COPY ./*.csproj .
RUN dotnet restore

#Build and publish project
COPY . ./
RUN dotnet publish -c Debug -o out

#Use runtime image to keep size dowm
FROM balenalib/intel-nuc-debian-dotnet:3.1-aspnet-run
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT  ["dotnet", "balenaLocatingDashboard.dll"]